### ISSUE TITLE
please add a LICENSE (file)

### ISSUE THREAD

**Issue by fischa** [xens/ripeinator#51]
I'd like to contribute more to this project but noticed it is missing a license that my current employer is ok with. Here is a list of licenses that would work:
- Public Domain
- BSD
- MIT
- Artistic License
- Python Software Foundation License
- PHP License
- zlib/libpng License
- Boost Software License
- OpenSSL/SSLeay License
- WTFPL
- ISC
- Apache 1.0, 1.1 or 2.0

Checkout the documentation Github has on this:
- https://choosealicense.com
- https://docs.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository
- https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

If you ask me I would go for one of these which are all pretty open:
- [Apache  License 2.0](https://choosealicense.com/licenses/apache-2.0/)
- [MIT](https://choosealicense.com/licenses/mit/)
- [Unlicense aka Public Domain](https://choosealicense.com/licenses/unlicense/)

What do you think @xens?

**Comment by xens** [comment]
thanks for the suggestion @fischa that's a good idea, I like best the [Apache Licence 2.0](https://choosealicense.com/licenses/apache-2.0) licences so I'm going to add it https://github.com/xens/ripeinator/pull/52.

When it comes to this project health I don't work with ISP-related activities anymore in my new job so it's hard to maintain it properly (difficult to validate changes + I won't commit much changes personally), so I'm wondering if this project should be re-hosted somewhere else maybe under a different namespace / organization. What do you think ?

**Comment by fischa** [comment]
Thanks. That would have been my first choice as well :)

I can see your trouble/problem. From top of my head I don't see a perfect place for it yet. I'll do some digging if there is a place in some RIPE community context. But in the meantime if you want to get rid of it - one option could be a transfer to my account. Thoughts?

**Comment by fischa** [comment]
Looks like there is only a RIPE Atlas Community as Github Org and no generic one that would be RIPE "related".

**Comment by xens** [comment]
I've invited you to join the project so you can also contribute more closely, and we can try to see / get in touch with the RIPE community that's a good idea. Closing this issue as the discussion diverged ;)
